server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telconnect_dev
    username: root
    password: mydb
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000